In [43]:
import pandas as pd

In [56]:
#data_20211 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20211.txt", delimiter = ";")
#data_20202 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20202.txt", delimiter = ";")
#data_20201 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20201.txt", delimiter = ";")
#data_20192 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20192.txt", delimiter = ";")
#data_20191 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20191.txt", delimiter = ";")
#data_20182 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20182.txt", delimiter = ";")
#data_20181 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20181.txt", delimiter = ";")
#data_20172 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20172.txt", delimiter = ";")
#data_20171 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20171.txt", delimiter = ";")
data_20162 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20162.txt", delimiter = ";")
data_20161 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20161.txt", delimiter = ";")
data_20152 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20152.txt", delimiter = ";")
data_20151 =  pd.read_csv("D:/Universidad/Maestria/Tesis/DATOS/Saber-11/Estudiantes/SB11_20151.txt", delimiter = ";")

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (11,13,14,15) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (9,10,11,12,13,14) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [78]:
def tratamiento_datos(df_colegio):
    data_dapurada2=df_colegio[['ESTU_GENERO','PERIODO','ESTU_TIENEETNIA',
           'FAMI_ESTRATOVIVIENDA', 'FAMI_PERSONASHOGAR',
           'FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE',
           'FAMI_TIENEINTERNET', 'FAMI_TIENECOMPUTADOR', 
                               #'FAMI_SITUACIONECONOMICA',
           #'ESTU_DEDICACIONLECTURADIARIA', 'ESTU_DEDICACIONINTERNET',
           'COLE_COD_DANE_ESTABLECIMIENTO', 'COLE_NOMBRE_ESTABLECIMIENTO',
           'COLE_GENERO', 'COLE_NATURALEZA', 'COLE_CALENDARIO', 'COLE_BILINGUE',
           'COLE_CARACTER', 'COLE_COD_DANE_SEDE', 'COLE_NOMBRE_SEDE',
           'COLE_SEDE_PRINCIPAL', 'COLE_AREA_UBICACION',
           'COLE_COD_MCPIO_UBICACION', 'COLE_MCPIO_UBICACION',
           'COLE_COD_DEPTO_UBICACION', 'COLE_DEPTO_UBICACION','PUNT_GLOBAL','PERCENTIL_GLOBAL']]
    data_dapurada2["CANTIDAD_ESTUDIANTES"]=1
    datos_dumis2=pd.get_dummies(data_dapurada2 ,columns=["ESTU_GENERO","ESTU_TIENEETNIA","FAMI_ESTRATOVIVIENDA",
                                                         "FAMI_PERSONASHOGAR", 'FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE',
                                                         'FAMI_TIENEINTERNET', 
                                                         'FAMI_TIENECOMPUTADOR'
                                                         #,"FAMI_SITUACIONECONOMICA","ESTU_DEDICACIONLECTURADIARIA"
                                                         #,"ESTU_DEDICACIONINTERNET"
                                                        ])
    datos_dumis2.head()
    data_max=datos_dumis2.groupby(['PERIODO','COLE_COD_DANE_ESTABLECIMIENTO', 'COLE_NOMBRE_ESTABLECIMIENTO',
           'COLE_GENERO', 'COLE_NATURALEZA', 'COLE_CALENDARIO', 'COLE_BILINGUE',
           'COLE_CARACTER', 'COLE_COD_DANE_SEDE', 'COLE_NOMBRE_SEDE',
           'COLE_SEDE_PRINCIPAL', 'COLE_AREA_UBICACION', 
           'COLE_COD_MCPIO_UBICACION', 'COLE_MCPIO_UBICACION',
           'COLE_COD_DEPTO_UBICACION', 'COLE_DEPTO_UBICACION'], as_index = False).agg({
        'PUNT_GLOBAL':['mean', 'median','std'],
                      'ESTU_GENERO_F':'sum',
                        'ESTU_GENERO_M':'sum',
                        'ESTU_TIENEETNIA_No':'sum',
                        'ESTU_TIENEETNIA_Si':'sum',
                        'FAMI_ESTRATOVIVIENDA_Estrato 1':'sum',
                        'FAMI_ESTRATOVIVIENDA_Estrato 2':'sum',
                        'FAMI_ESTRATOVIVIENDA_Estrato 3':'sum',
                        'FAMI_ESTRATOVIVIENDA_Estrato 4':'sum',
                        'FAMI_ESTRATOVIVIENDA_Estrato 5':'sum',
                        'FAMI_ESTRATOVIVIENDA_Estrato 6':'sum',
                        #'FAMI_ESTRATOVIVIENDA_Sin Estrato':'sum',
                        #'FAMI_PERSONASHOGAR_1 a 2':'sum',
                        #'FAMI_PERSONASHOGAR_3 a 4':'sum',
                        #'FAMI_PERSONASHOGAR_5 a 6':'sum',
                        #'FAMI_PERSONASHOGAR_7 a 8':'sum',
                        #'FAMI_PERSONASHOGAR_9 o más':'sum',
                        'FAMI_EDUCACIONPADRE_Educación profesional completa':'sum',
                        'FAMI_EDUCACIONPADRE_Educación profesional incompleta':'sum',
                        'FAMI_EDUCACIONPADRE_Ninguno':'sum',
                        #'FAMI_EDUCACIONPADRE_No Aplica':'sum',
                        'FAMI_EDUCACIONPADRE_No sabe':'sum',
                        'FAMI_EDUCACIONPADRE_Postgrado':'sum',
                        'FAMI_EDUCACIONPADRE_Primaria completa':'sum',
                        'FAMI_EDUCACIONPADRE_Primaria incompleta':'sum',
                        'FAMI_EDUCACIONPADRE_Secundaria (Bachillerato) completa':'sum',
                        'FAMI_EDUCACIONPADRE_Secundaria (Bachillerato) incompleta':'sum',
                        'FAMI_EDUCACIONPADRE_Técnica o tecnológica completa':'sum',
                        'FAMI_EDUCACIONPADRE_Técnica o tecnológica incompleta':'sum',
                        'FAMI_EDUCACIONMADRE_Educación profesional completa':'sum',
                        'FAMI_EDUCACIONMADRE_Educación profesional incompleta':'sum',
                        'FAMI_EDUCACIONMADRE_Ninguno':'sum',
                        #'FAMI_EDUCACIONMADRE_No Aplica':'sum',
                        'FAMI_EDUCACIONMADRE_No sabe':'sum',
                        'FAMI_EDUCACIONMADRE_Postgrado':'sum',
                        'FAMI_EDUCACIONMADRE_Primaria completa':'sum',
                        'FAMI_EDUCACIONMADRE_Primaria incompleta':'sum',
                        'FAMI_EDUCACIONMADRE_Secundaria (Bachillerato) completa':'sum',
                        'FAMI_EDUCACIONMADRE_Secundaria (Bachillerato) incompleta':'sum',
                        'FAMI_EDUCACIONMADRE_Técnica o tecnológica completa':'sum',
                        'FAMI_EDUCACIONMADRE_Técnica o tecnológica incompleta':'sum',
                        'FAMI_TIENEINTERNET_No':'sum',
                        'FAMI_TIENEINTERNET_Si':'sum',
                        'FAMI_TIENECOMPUTADOR_No':'sum',
                        'FAMI_TIENECOMPUTADOR_Si':'sum',
                        #'FAMI_SITUACIONECONOMICA_Igual':'sum',
                        #'FAMI_SITUACIONECONOMICA_Mejor':'sum',
                        #'FAMI_SITUACIONECONOMICA_Peor':'sum',
                        #'ESTU_DEDICACIONLECTURADIARIA_30 minutos o menos':'sum',
                        #'ESTU_DEDICACIONLECTURADIARIA_Entre 1 y 2 horas':'sum',
                        #'ESTU_DEDICACIONLECTURADIARIA_Entre 30 y 60 minutos':'sum',
                        #'ESTU_DEDICACIONLECTURADIARIA_Más de 2 horas':'sum',
                        #'ESTU_DEDICACIONLECTURADIARIA_No leo por entretenimiento':'sum',
                        #'ESTU_DEDICACIONINTERNET_30 minutos o menos':'sum',
                        #'ESTU_DEDICACIONINTERNET_Entre 1 y 3 horas':'sum',
                        #'ESTU_DEDICACIONINTERNET_Entre 30 y 60 minutos':'sum',
                        #'ESTU_DEDICACIONINTERNET_Más de 3 horas':'sum',
                        #'ESTU_DEDICACIONINTERNET_No Navega Internet':'sum',
                        "CANTIDAD_ESTUDIANTES":'sum'})
    return data_max

In [79]:
#data_20211d=tratamiento_datos(data_20211)
#data_20202d=tratamiento_datos(data_20202)
#data_20201d=tratamiento_datos(data_20201)
#data_20192d=tratamiento_datos(data_20192)
#data_20191d=tratamiento_datos(data_20191)
#data_20182d=tratamiento_datos(data_20182)
#data_20181d=tratamiento_datos(data_20181)
#data_20172d=tratamiento_datos(data_20172)
#data_20171d=tratamiento_datos(data_20171)
data_20162d=tratamiento_datos(data_20162)
data_20161d=tratamiento_datos(data_20161)
data_20152d=tratamiento_datos(data_20152)
data_20151d=tratamiento_datos(data_20151)

<ipython-input-78-2590a3769d96>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_dapurada2["CANTIDAD_ESTUDIANTES"]=1

KeyError: "['PERCENTIL_GLOBAL'] not in index"

In [81]:
df_colegio = pd.concat([data_20211d,data_20202d,
                        data_20201d,
                        data_20192d,
                        data_20191d,
                       data_20182d,
                       data_20181d,
                       data_20172d,
                       data_20171d,
                       data_20162d,
                       data_20161d
                       #data_20152d,
                       #data_20151d
                       ], ignore_index=True, sort=False)

In [84]:
df_colegio.to_excel("D:/Universidad/Maestria/Tesis/DATOS/Data_Agrupada_depurada/datos_planteles_agrupada_20202.xlsx")

In [85]:
df_colegio

      CANTIDAD_ESTUDIANTES COLE_AREA_UBICACION COLE_BILINGUE COLE_CALENDARIO  \
                       sum
0                        1              URBANO             N               A
1                        1              URBANO             N               A
2                        1              URBANO             N               A
3                        1              URBANO             N               A
4                        1              URBANO             S               A
...                    ...                 ...           ...             ...
41863                  112               RURAL             N               B
41864                   20              URBANO             S               B
41865                  123              URBANO             N               B
41866                    9               RURAL             S               B
41867                   11               RURAL             N               B

           COLE_CARACTER COLE_COD_DANE_ESTABLECIMIENTO COLE_COD_DANE_SEDE  \

0      TÉCNICO/ACADÉMICO                  105001000621       105001000621
1      TÉCNICO/ACADÉMICO                  105001000931       105001000931
2              ACADÉMICO                  105001001651       105001001651
3              ACADÉMICO                  105001002020       105001002020
4      TÉCNICO/ACADÉMICO                  105001002488       105001002046
...                  ...                           ...                ...
41863  TÉCNICO/ACADÉMICO                  476248000478       476248000478
41864          ACADÉMICO                  476520006324       476520006324
41865            TÉCNICO                  476520007207       476520007207
41866          ACADÉMICO                  476892099710       476892099710
41867          ACADÉMICO                  476892099728       476892099728

      COLE_COD_DEPTO_UBICACION COLE_COD_MCPIO_UBICACION COLE_DEPTO_UBICACION  \

0                            5                     5001            ANTIOQUIA
1                            5                     5001            ANTIOQUIA
2                            5                     5001            ANTIOQUIA
3                            5                     5001            ANTIOQUIA
4                            5                     5001            ANTIOQUIA
...                        ...                      ...                  ...
41863                       76                    76248                VALLE
41864                       76                    76520                VALLE
41865                       76                    76520                VALLE
41866                       76                    76892                VALLE
41867                       76                    76892                VALLE

       ... FAMI_SITUACIONECONOMICA_Mejor FAMI_SITUACIONECONOMICA_Peor  \
       ...                           sum                          sum
0      ...                           0.0                          0.0
1      ...                           0.0                          0.0
2      ...                           0.0                          0.0
3      ...                           0.0                          1.0
4      ...                           0.0                          0.0
...    ...                           ...                          ...
41863  ...                           NaN                          NaN
41864  ...                           NaN                          NaN
41865  ...                           NaN                          NaN
41866  ...                           NaN                          NaN
41867  ...                           NaN                          NaN

      FAMI_TIENECOMPUTADOR_No FAMI_TIENECOMPUTADOR_Si FAMI_TIENEINTERNET_No  \
                          sum                     sum                   sum
0                         0.0                     1.0                   0.0
1                         0.0                     0.0                   0.0
2                         0.0                     1.0                   0.0
3                         0.0                     1.0                   0.0
4                         0.0                     1.0                   0.0
...                       ...                     ...                   ...
41863                     7.0                   105.0                   9.0
41864                     0.0                    20.0                   0.0
41865                    10.0                   113.0                   8.0
41866                     1.0                     8.0                   0.0
41867                     0.0                    11.0                   2.0

      FAMI_TIENEINTERNET_Si PERIODO PUNT_GLOBAL
                        sum                mean median        std
0                       0.0   20211  264.000000  264.0        NaN
1                       0.0   20211  273.000000  273.0        NaN
2                       1.0   20211  332.000000  332.0        NaN
3                       1.0   20211  242.000000  242.0        NaN
4                       1.0   20211  246.000000  246.0        NaN
...                     ...     ...         ...    ...        ...
41863                 103.0   20161  281.098214  276.0  46.001559
41864                  20.0   20161  297.450000  292.5  35.704157
41865                 115.0   20161  269.276423  272.0  41.181983
41866                   9.0   20161  355.555556  368.0  39.386264
41867                   9.0   20161  277.818182  262.0  48.010037

[41868 rows x 77 columns]

In [60]:
print(data_20162.columns)

Index(['ESTU_TIPODOCUMENTO', 'ESTU_NACIONALIDAD', 'ESTU_GENERO',
       'ESTU_FECHANACIMIENTO', 'PERIODO', 'ESTU_CONSECUTIVO',
       'ESTU_ESTUDIANTE', 'ESTU_PAIS_RESIDE', 'ESTU_TIENEETNIA', 'ESTU_ETNIA',
       'ESTU_DEPTO_RESIDE', 'ESTU_COD_RESIDE_DEPTO', 'ESTU_MCPIO_RESIDE',
       'ESTU_COD_RESIDE_MCPIO', 'ESTU_AREARESIDE', 'ESTU_VALORPENSIONCOLEGIO',
       'ESTU_VECESPRESENTOEXAMEN', 'FAMI_EDUCACIONPADRE',
       'FAMI_EDUCACIONMADRE', 'FAMI_OCUPACIONPADRE', 'FAMI_OCUPACIONMADRE',
       'FAMI_NUMHERMANOS', 'FAMI_ESTRATOVIVIENDA', 'FAMI_NIVELSISBEN',
       'FAMI_PERSONASHOGAR', 'FAMI_CUARTOSHOGAR', 'FAMI_PISOSHOGAR',
       'FAMI_TIENEINTERNET', 'FAMI_TIENECOMPUTADOR', 'FAMI_TIENELAVADORA',
       'FAMI_TIENEMICROONDAS', 'FAMI_TIENEHORNO', 'FAMI_TIENESERVICIOTV',
       'FAMI_TIENEAUTOMOVIL', 'FAMI_TIENEDVD', 'FAMI_TELEFONO',
       'FAMI_NUMLIBROS', 'FAMI_INGRESOFMILIARMENSUAL',
       'ESTU_TRABAJAACTUALMENTE', 'ESTU_RECIBESALARIO', 'COLE_CODIGO_ICFES',
       'COLE_COD_DANE_ESTABLECIMIENTO', 'COLE_NOMBRE_ESTABLECIMIENTO',
       'COLE_GENERO', 'COLE_NATURALEZA', 'COLE_CALENDARIO', 'COLE_BILINGUE',
       'COLE_CARACTER', 'COLE_COD_DANE_SEDE', 'COLE_NOMBRE_SEDE',
       'COLE_SEDE_PRINCIPAL', 'COLE_AREA_UBICACION', 'COLE_JORNADA',
       'COLE_COD_MCPIO_UBICACION', 'COLE_MCPIO_UBICACION',
       'COLE_COD_DEPTO_UBICACION', 'COLE_DEPTO_UBICACION',
       'ESTU_PRIVADO_LIBERTAD', 'ESTU_COD_MCPIO_PRESENTACION',
       'ESTU_MCPIO_PRESENTACION', 'ESTU_DEPTO_PRESENTACION',
       'ESTU_COD_DEPTO_PRESENTACION', 'PUNT_LECTURA_CRITICA',
       'PERCENTIL_LECTURA_CRITICA', 'DESEMP_LECTURA_CRITICA',
       'PUNT_MATEMATICAS', 'PERCENTIL_MATEMATICAS', 'DESEMP_MATEMATICAS',
       'PUNT_C_NATURALES', 'PERCENTIL_C_NATURALES', 'DESEMP_C_NATURALES',
       'PUNT_SOCIALES_CIUDADANAS', 'PERCENTIL_SOCIALES_CIUDADANAS',
       'DESEMP_SOCIALES_CIUDADANAS', 'PUNT_INGLES', 'PERCENTIL_INGLES',
       'DESEMP_INGLES', 'PUNT_GLOBAL', 'PERCENTIL_GLOBAL',
       'ESTU_INSE_INDIVIDUAL', 'ESTU_NSE_INDIVIDUAL',
       'ESTU_NSE_ESTABLECIMIENTO', 'ESTU_ESTADOINVESTIGACION',
       'ESTU_PILOPAGA'],
      dtype='object')